#' solidwastekampala: Quantity and Composition of Domestic Solid Waste in Kampala City
#'
#' Household-level results of a seven-day domestic solid waste
#' characterisation in three parishes of Kampala City, Uganda (Bwaise I =
#' low income, Bukoto I = middle income, Ggaba = high income). For each of
#' the 103 analyzed households the data record socio-economic
#' characteristics, the measured mass of ten waste categories, and the
#' derived per-household metrics (total, per-day, per-capita, volume, and
#' density).
#' 
#' @format A tibble with 103 rows and 37 variables
#' \describe{
#'   \item{id}{Package-level unique household identifier (1-103), following the row numbering of the All_data sheet in the raw workbook (Bwaise I, then Bukoto I, then Ggaba).}
#'   \item{household_id}{Household label as recorded on the area sheet (for example Household_7); values repeat across parishes and contain gaps, so id is the unique key.}
#'   \item{division}{Kampala City division the household is located in (Kawempe, Makindye, or Nakawa).}
#'   \item{parish}{Study parish the household is located in (Bwaise I = low income, Bukoto I = middle income, Ggaba = high income area).}
#'   \item{zone}{Administrative zone within the parish where the household is located.}
#'   \item{income_level}{Income level of the household's study area as classified in the study design; ordered factor with levels low < middle < high.}
#'   \item{occupants}{Number of people living in the household during the 7-day waste collection period.}
#'   \item{age_head}{Age of the household head in years; ordered factor with levels 18-35 < 36-60 < >60.}
#'   \item{gender_head}{Gender of the household head (Female or Male).}
#'   \item{education_head}{Highest education level of the household head; ordered factor with levels Illiterate < Primary < Secondary < Tertiary.}
#'   \item{profession_head}{Profession of the household head (Business, Government employee, Housewife, Private employee, or Retired).}
#'   \item{monthly_income_ugx}{Monthly household income band in Uganda shillings (UGX); ordered factor with levels <500,000 < 500,000-1,000,000 < 1,000,000-3,000,000 < >3,000,000.}
#'   \item{respondent}{Household member who answered the questionnaire (Household head, Spouse, Son/daughter, or Niece/nephew).}
#'   \item{period_of_stay}{How long the household has lived at the premises; ordered factor with levels <1 year < 1-3 years < 3-5 years < >5 years.}
#'   \item{occupancy}{Occupancy status of the premises (Occupied by owner or Rented).}
#'   \item{housing_quality}{Type of dwelling as a proxy for housing quality (Bungalow, Story building, or Temporary).}
#'   \item{roof_material}{Main roof material of the dwelling (Cemented, Iron sheets, Iron sheets/tiles, or Tiles); Bwaise I recorded only the combined Iron sheets/tiles category.}
#'   \item{wall_material}{Main wall material of the dwelling (Bricks, Concrete blocks, or Mud/poles).}
#'   \item{floor_material}{Main floor material of the dwelling (Cemented, Mud, or Tiles).}
#'   \item{water_access}{Main drinking water access of the household (House connection, Stand pipe, or Yard tap).}
#'   \item{sanitation_facility}{Whether the household's sanitation facility is shared with other households (Shared facilities or Not shared facilities).}
#'   \item{road_condition}{Condition of the access road to the household (Paved or Unpaved).}
#'   \item{waste_food_kg}{Mass of food waste generated by the household over the 7-day collection period, in kilograms (ASTM waste category).}
#'   \item{waste_garden_kg}{Mass of garden waste generated by the household over the 7-day collection period, in kilograms (ASTM waste category).}
#'   \item{waste_wood_kg}{Mass of wood waste generated by the household over the 7-day collection period, in kilograms (ASTM waste category).}
#'   \item{waste_textiles_kg}{Mass of textile waste generated by the household over the 7-day collection period, in kilograms (ASTM waste category).}
#'   \item{waste_paper_kg}{Mass of paper waste generated by the household over the 7-day collection period, in kilograms (ASTM waste category).}
#'   \item{waste_polythene_kg}{Mass of polythene waste generated by the household over the 7-day collection period, in kilograms (ASTM waste category).}
#'   \item{waste_plastics_kg}{Mass of plastic waste generated by the household over the 7-day collection period, in kilograms (ASTM waste category).}
#'   \item{waste_glass_kg}{Mass of glass waste generated by the household over the 7-day collection period, in kilograms (ASTM waste category).}
#'   \item{waste_metals_kg}{Mass of metal waste generated by the household over the 7-day collection period, in kilograms (ASTM waste category); for Ggaba Household_7 the value 2.674 was stored as text in the raw sheet and is excluded from that household's recorded waste_total_kg.}
#'   \item{waste_other_kg}{Mass of waste not covered by the other nine categories, generated by the household over the 7-day collection period, in kilograms (ASTM waste category).}
#'   \item{waste_total_kg}{Total mass of waste generated by the household over the 7-day collection period, in kilograms, as recorded in the raw sheet (SUM of the ten category columns).}
#'   \item{waste_per_day_kg}{Mean daily mass of waste generated by the household, in kilograms per day (waste_total_kg divided by 7).}
#'   \item{waste_per_capita_kg}{Mean daily mass of waste generated per household member, in kilograms per person per day (waste_per_day_kg divided by occupants).}
#'   \item{volume_l}{Volume of the waste generated by the household over the 7-day collection period, in litres.}
#'   \item{density_kg_l}{Bulk density of the generated waste, in kilograms per litre; multiply by 1000 for kg/m3 as reported in the manuscript.}
#' }
#' @source Data collected by the study team of Katukiza et al. (Makerere
#'   University) for the manuscript "Quantity and Composition of Domestic
#'   Solid Waste in Kampala City as Influenced by Socio-Economic Factors".
#'   Raw workbook preserved in \code{data-raw/data_sheets_with_analysis.xlsx}.
#' @examples
#' head(solidwastekampala)
#' summary(solidwastekampala$waste_per_capita_kg)
#' table(solidwastekampala$income_level)
"solidwastekampala"
